version: "3.8"

services:
  database01:
    container_name: database-master
    image: postgres:13
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order
    ports:
      - 5432
    volumes:
      - ./data/master:/var/lib/postgresql/data
    networks:
      postgres:
        ipv4_address: 10.0.3.200
  
  database02:
    container_name: database-slave-1
    image: postgres:13
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order
    ports:
      - 5432
    volumes:
      # Setup replica "pg_basebackup -R -D /var/lib/postgresql/repl -Fp -Xs -v -P -h 10.0.3.200 -p 5432 -U repuser"
      # - ./data/slave1:/var/lib/postgresql/data
      # - ./data/repl1:/var/lib/postgresql/repl
      # After Setup switch dir
      - ./data/repl1:/var/lib/postgresql/data
    depends_on:
      - database01
    networks:
      postgres:
        ipv4_address: 10.0.3.201
  
  database03:
    container_name: database-slave-2
    image: postgres:13
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order
    ports:
      - 5432
    volumes:
      # Setup replica "pg_basebackup -R -D /var/lib/postgresql/repl -Fp -Xs -v -P -h 10.0.3.200 -p 5432 -U repuser"
      # - ./data/slave2:/var/lib/postgresql/data
      # - ./data/repl2:/var/lib/postgresql/repl
      # After Setup switch dir
      - ./data/repl2:/var/lib/postgresql/data
    depends_on:
      - database01
    networks:
      postgres:
        ipv4_address: 10.0.3.202

  lb:
    image: haproxy
    container_name: lb-haproxy
    ports:
        - "7000:7000"
        - "5000:5000"
        - "5001:5001"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - database01
      - database02
      - database03
    networks:
      postgres:
        ipv4_address: 10.0.3.2

volumes:
  db:
  
networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/24
          gateway: 10.0.3.1